### ISSUE TITLE
ERROR libjemalloc.so

### ISSUE THREAD

**Issue by AdsonCicilioti** [VisiStruct/EngineScript#2]
Obtaining the following error during Setup:

```
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libjemalloc.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
```
Looking at the file **initial-setup.sh**, at line [80](https://github.com/VisiStruct/EngineScript/blob/37e7216d2cc7f2d5f9e37e2ca768806f7a42bef0/Initial-Setup.sh#L80), we see the package libjemalloc1. and on line [133](https://github.com/VisiStruct/EngineScript/blob/37e7216d2cc7f2d5f9e37e2ca768806f7a42bef0/Initial-Setup.sh#L133), you added the path to the `libjemalloc.so` file. The correct one would be `libjemalloc.so.1`.

The environment is a VPS Vultr of 1gb ram, 1vcpu w 25gb ssd with UBUNTU 18.04.

**Comment by dyrer** [comment]
hello
I have exactly the same problem with errors Ubuntu 18.04 Hetzner
https://www.screencast.com/t/M1ESPvtd

**Comment by AdsonCicilioti** [comment]
In my fork, i fixed renaming libjemalloc.so to libjemalloc.so.1 on line 133.
but now, the problem is with nginx... `systemctl status nginx` returns `nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No such file or directory`.

`nginx -t` show ausence of installation.

**Comment by PDowney** [comment]
I just pushed some updates to the development branch that should solve the jemalloc issue. For the nginx not starting issue it looks like the script wasn't able to complete the nginx install and failed. 

Try running the Development branch on a fresh server.

**Comment by AdsonCicilioti** [comment]
Thanks @PDowney ! I will test.

**Comment by AdsonCicilioti** [comment]
Nice!! Dev branch works fine!!

**Comment by AdsonCicilioti** [comment]
@PDowney, explain me better how to add a site / domain ...
My problem is with the step of pasting Certificate of Origin and My Private Key.
What would the Certificate of Origin be? Do I create this in my CloudFlare account?
Would the private key be my id_rsa from my computer?

Thank you very much in advance!

**Comment by AdsonCicilioti** [comment]
I set Password for root in Mysql, and get error during Add Domain Proccess. How i can solve this?

**Comment by AdsonCicilioti** [comment]
Thanks! Works fine now!
